server:
  port: 8098

spring:
  application:
    name: SUPPORT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/bankDB?createDatabaseIfNotExist=true
    username: postgres
    password: user24
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect